### ISSUE TITLE
Plexus Cipher 3.0.0

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/plexus-cipher#46]
This issue will cover the work for Plexus Cipher 3.0

**Comment by slachiewicz** [comment]
what about changing also package from `org.sonatype.plexus.components.cipher` ?

**Comment by cstamas** [comment]
wow, i completely forgot about that

**Comment by cstamas** [comment]
I ready for release

**Comment by cstamas** [comment]
Done
